baseurl = "#{hostname}#"
languageCode = "en-us"
title = "Cloud with Chris"
theme = "castanet"
googleAnalytics = ""
paginate = "9"
buildFuture = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "Episodes"
    identifier = "0-episodes"
    url = "/"


[[Menu.Main]]
    name = "Upcoming"
    identifier = "1-upcoming"
    url = "/upcoming"

[[Menu.Main]]
    name = "Suggest a topic"
    identifier = "2-topics"
    url = "https://forms.office.com/Pages/ResponsePage.aspx?id=I8_hAe_rSkSatzbwI0Rs1nhBo3a5mW9AuJOwL1Kt0n9UQVcyOFZFNkdXU0FGNTM0Uk0zUEdPT1VFNy4u"

[[Menu.Main]]
    name = "Become a Guest"
    identifier = "3-guestsignup"
    url = "https://calendly.com/cloudwithchris"

[[Menu.Main]]
    name = "Guests"
    identifier = "4-guests"
    url = "/guest"

[[Menu.Main]]
    name = "About Chris"
    identifier = "5-about"
    url = "https://www.christianreddington.co.uk"

[params]
mainSections = ["episode"]
site_theme = "grey"
# site_layout = "grid"
site_layout = "row"
enable_jumbo = "true"
enable_show_next_episode = true
# enable_jumbo = "false"
# truncate = "100"
about_logo = "/img/cloudwithchrislogo.png"
copyright_notice = "Copyright 2020 [Chris Reddington](https://www.christianreddington.co.uk), Proudly running using [Hugo](https://gohugo.io/) and the [Castanet Theme](https://themes.gohugo.io/castanet/). Microphone Icon in logo is made by [Smashicons](https://www.flaticon.com/authors/smashicons) from [www.flaticon.com](https://www.flaticon.com/).  Cloud with Chris is a community-driven personal podcast. Content from episodes do not represent the views of any company or organisation."
itunes_subscribe = "https://podcasts.apple.com/gb/podcast/cloud-with-chris/id1499633784"
#android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
spotify_subscribe = "https://open.spotify.com/show/3oBrdKm5grzl58GBiV0j2y"
google_play_subscribe = "https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Icbsoegu6uvdlor4p4ukknrnel4?t%3DCloud_with_Chris%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16"
stitcher_subscribe = "https://www.stitcher.com/s?fid=507667&refid=stpr"
#soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
pocketcasts_subscribe = "https://pca.st/u5t985sn"
##mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
##rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Exploring Cloud concepts with Chris Reddington (Welsh Tech Geek, Cloud Advocate, Musical Theatre Enthusiast and Improving Improviser!). We will regularly invite guests to talk about their experiences with the cloud and hear about some of the lessons learned around their cloud journey. Cloud with Chris is a community-driven personal podcast. Content from episodes do not represent the views of any company or organisation."
media_prefix = "https://podcasts.cloudwithchris.com/"
disqusShortname = ""

  [params.feed]
    copyright = "Copyright 2020 Chris Reddington" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "Exploring Cloud concepts with Chris Reddington!" #no markdown or HTML
    itunes_author = "Chris Reddington" #no markdown or HTML
    itunes_summary = "Exploring Cloud concepts with Chris Reddington (Welsh Tech Geek, Cloud Advocate, Musical Theatre Enthusiast and Improving Improviser!). We will regularly invite guests to talk about their experiences with the cloud and hear about some of the lessons learned around their cloud journey."
    itunes_owner_name = "Chris Reddington"
    itunes_owner_email = "chris@cloudwithchris.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.cloudwithchris.com/img/cloudwithchrislogo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Podcasting"
    itunes_second_sub_category = "Software How-To"
    language = "en-us"
    explicit = "no"
    
  [params.social]
    facebook = "CloudWithChris"
    #facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "CloudWithChris"
    twitter_domain = "cloudwithchris.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    youtube = "c/CloudWithChris"

  [params.authors]
    [params.authors.Chris]
      name	= "Chris Reddington"
      thumbnail = "img/hosts/chris-headshot.jpg"
      bio = "Chris is a Welsh Tech Geek, Senior FastTrack for Azure Engineer, Musical Theatre Enthusiast and Improving Improviser!"
      [params.authors.Chris.social]
        github = "christianreddington"
        twitter = "reddobowen"
        linkedin = "christianreddington"
        homepage = "https://www.christianreddington.co.uk"
